SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS COMMENT_INFO;
DROP TABLE IF EXISTS BOARD_INFO;
DROP TABLE IF EXISTS USER_INFO;




/* Create Tables */

CREATE TABLE BOARD_INFO
(
	BINUM int unsigned NOT NULL AUTO_INCREMENT,
	BITITLE varchar(3000) NOT NULL,
	BITEXT text NOT NULL,
	BIFILE varchar(50),
	BICREDAT datetime NOT NULL,
	BIMODDAT datetime NOT NULL,
	BICNT int DEFAULT 0 NOT NULL,
	BIACTIVE tinyint DEFAULT 1 NOT NULL,
	UINUM int unsigned NOT NULL,
	PRIMARY KEY (BINUM)
);


CREATE TABLE COMMENT_INFO
(
	CINUM int unsigned NOT NULL AUTO_INCREMENT,
	CITEXT varchar(3000) NOT NULL,
	CICREDAT datetime NOT NULL,
	CIMODDAT datetime NOT NULL,
	UINUM int unsigned NOT NULL,
	BINUM int unsigned NOT NULL,
	PRIMARY KEY (CINUM)
);


CREATE TABLE USER_INFO
(
	UINUM int unsigned NOT NULL AUTO_INCREMENT,
	UIID varchar(30) NOT NULL,
	UIPWD varchar(30) NOT NULL,
	UINAME varchar(30) NOT NULL,
	UIEMAIL varchar(100),
	PRIMARY KEY (UINUM),
	UNIQUE (UIID)
);



/* Create Foreign Keys */

ALTER TABLE COMMENT_INFO
	ADD FOREIGN KEY (BINUM)
	REFERENCES BOARD_INFO (BINUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BOARD_INFO
	ADD FOREIGN KEY (UINUM)
	REFERENCES USER_INFO (UINUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE COMMENT_INFO
	ADD FOREIGN KEY (UINUM)
	REFERENCES USER_INFO (UINUM)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



