package com.board.bdi.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * 댓글정보 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CommentInfoVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 댓글번호. */
	private Integer cinum;

	/** 댓글내용. */
	private String citext;

	/** 댓글등록일. */
	private Date cicredat;

	/** 댓글수정일. */
	private Date cimoddat;

	/** 사용자_정보. */
	private UserInfoVo userInfo;

	/** 게시판. */
	private BoardInfoVo boardInfo;

	/**
	 * 생성자.
	 */
	public CommentInfoVo() {
	}

	/**
	 * 댓글번호을 설정합니다..
	 * 
	 * @param cinum
	 *            댓글번호
	 */
	public void setCinum(Integer cinum) {
		this.cinum = cinum;
	}

	/**
	 * 댓글번호을 가져옵니다..
	 * 
	 * @return 댓글번호
	 */
	public Integer getCinum() {
		return this.cinum;
	}

	/**
	 * 댓글내용을 설정합니다..
	 * 
	 * @param citext
	 *            댓글내용
	 */
	public void setCitext(String citext) {
		this.citext = citext;
	}

	/**
	 * 댓글내용을 가져옵니다..
	 * 
	 * @return 댓글내용
	 */
	public String getCitext() {
		return this.citext;
	}

	/**
	 * 댓글등록일을 설정합니다..
	 * 
	 * @param cicredat
	 *            댓글등록일
	 */
	public void setCicredat(Date cicredat) {
		this.cicredat = cicredat;
	}

	/**
	 * 댓글등록일을 가져옵니다..
	 * 
	 * @return 댓글등록일
	 */
	public Date getCicredat() {
		return this.cicredat;
	}

	/**
	 * 댓글수정일을 설정합니다..
	 * 
	 * @param cimoddat
	 *            댓글수정일
	 */
	public void setCimoddat(Date cimoddat) {
		this.cimoddat = cimoddat;
	}

	/**
	 * 댓글수정일을 가져옵니다..
	 * 
	 * @return 댓글수정일
	 */
	public Date getCimoddat() {
		return this.cimoddat;
	}

	/**
	 * 사용자_정보을 설정합니다..
	 * 
	 * @param userInfo
	 *            사용자_정보
	 */
	public void setUserInfo(UserInfoVo userInfo) {
		this.userInfo = userInfo;
	}

	/**
	 * 사용자_정보을 가져옵니다..
	 * 
	 * @return 사용자_정보
	 */
	public UserInfoVo getUserInfo() {
		return this.userInfo;
	}

	/**
	 * 게시판을 설정합니다..
	 * 
	 * @param boardInfo
	 *            게시판
	 */
	public void setBoardInfo(BoardInfoVo boardInfo) {
		this.boardInfo = boardInfo;
	}

	/**
	 * 게시판을 가져옵니다..
	 * 
	 * @return 게시판
	 */
	public BoardInfoVo getBoardInfo() {
		return this.boardInfo;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((cinum == null) ? 0 : cinum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		CommentInfoVo other = (CommentInfoVo) obj;
		if (cinum == null) {
			if (other.cinum != null) {
				return false;
			}
		} else if (!cinum.equals(other.cinum)) {
			return false;
		}
		return true;
	}

}
