package com.board.bdi.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 사용자_정보 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserInfoVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 유저정보번호. */
	private Integer uinum;

	/** 유저정보아이디. */
	private String uiid;

	/** 유저정보비밀번호. */
	private String uipwd;

	/** 유저정보이름. */
	private String uiname;

	/** 유저정보이메일. */
	private String uiemail;

	/** 게시판 목록. */
	private Set<BoardInfoVo> boardInfoSet;

	/** 댓글정보 목록. */
	private Set<CommentInfoVo> commentInfoSet;

	/**
	 * 생성자.
	 */
	public UserInfoVo() {
		this.boardInfoSet = new HashSet<BoardInfoVo>();
		this.commentInfoSet = new HashSet<CommentInfoVo>();
	}

	/**
	 * 유저정보번호을 설정합니다..
	 * 
	 * @param uinum
	 *            유저정보번호
	 */
	public void setUinum(Integer uinum) {
		this.uinum = uinum;
	}

	/**
	 * 유저정보번호을 가져옵니다..
	 * 
	 * @return 유저정보번호
	 */
	public Integer getUinum() {
		return this.uinum;
	}

	/**
	 * 유저정보아이디을 설정합니다..
	 * 
	 * @param uiid
	 *            유저정보아이디
	 */
	public void setUiid(String uiid) {
		this.uiid = uiid;
	}

	/**
	 * 유저정보아이디을 가져옵니다..
	 * 
	 * @return 유저정보아이디
	 */
	public String getUiid() {
		return this.uiid;
	}

	/**
	 * 유저정보비밀번호을 설정합니다..
	 * 
	 * @param uipwd
	 *            유저정보비밀번호
	 */
	public void setUipwd(String uipwd) {
		this.uipwd = uipwd;
	}

	/**
	 * 유저정보비밀번호을 가져옵니다..
	 * 
	 * @return 유저정보비밀번호
	 */
	public String getUipwd() {
		return this.uipwd;
	}

	/**
	 * 유저정보이름을 설정합니다..
	 * 
	 * @param uiname
	 *            유저정보이름
	 */
	public void setUiname(String uiname) {
		this.uiname = uiname;
	}

	/**
	 * 유저정보이름을 가져옵니다..
	 * 
	 * @return 유저정보이름
	 */
	public String getUiname() {
		return this.uiname;
	}

	/**
	 * 유저정보이메일을 설정합니다..
	 * 
	 * @param uiemail
	 *            유저정보이메일
	 */
	public void setUiemail(String uiemail) {
		this.uiemail = uiemail;
	}

	/**
	 * 유저정보이메일을 가져옵니다..
	 * 
	 * @return 유저정보이메일
	 */
	public String getUiemail() {
		return this.uiemail;
	}

	/**
	 * 게시판 목록을 설정합니다..
	 * 
	 * @param boardInfoSet
	 *            게시판 목록
	 */
	public void setBoardInfoSet(Set<BoardInfoVo> boardInfoSet) {
		this.boardInfoSet = boardInfoSet;
	}

	/**
	 * 게시판를 추가합니다..
	 * 
	 * @param boardInfo
	 *            게시판
	 */
	public void addBoardInfo(BoardInfoVo boardInfo) {
		this.boardInfoSet.add(boardInfo);
	}

	/**
	 * 게시판 목록을 가져옵니다..
	 * 
	 * @return 게시판 목록
	 */
	public Set<BoardInfoVo> getBoardInfoSet() {
		return this.boardInfoSet;
	}

	/**
	 * 댓글정보 목록을 설정합니다..
	 * 
	 * @param commentInfoSet
	 *            댓글정보 목록
	 */
	public void setCommentInfoSet(Set<CommentInfoVo> commentInfoSet) {
		this.commentInfoSet = commentInfoSet;
	}

	/**
	 * 댓글정보를 추가합니다..
	 * 
	 * @param commentInfo
	 *            댓글정보
	 */
	public void addCommentInfo(CommentInfoVo commentInfo) {
		this.commentInfoSet.add(commentInfo);
	}

	/**
	 * 댓글정보 목록을 가져옵니다..
	 * 
	 * @return 댓글정보 목록
	 */
	public Set<CommentInfoVo> getCommentInfoSet() {
		return this.commentInfoSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((uinum == null) ? 0 : uinum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		UserInfoVo other = (UserInfoVo) obj;
		if (uinum == null) {
			if (other.uinum != null) {
				return false;
			}
		} else if (!uinum.equals(other.uinum)) {
			return false;
		}
		return true;
	}

}
